USE IRYS;
GO
INSERT INTO dbo.CustomerArea
(
	AreaCode,
	AreaName
)
SELECT 
	TRY_CONVERT(INT, c.AREACODE) AS AREACODE,
	NULLIF(LTRIM(RTRIM(c.AREANAME)), '') AS AREANAME
FROM FoxProLegacy.dbo.CUSTAREA AS c;
GO