USE IRYS;
GO
INSERT INTO dbo.Employees
(
	Id,
	FirstName,
	MiddleName,
	LastName,
	NickName,
	Position,
	Address,
	City,
	Province,
	ZipCode,
	Phone,
	BirthDate,
	Sex,
	DateHired,
	SSS,
	GroupId,
	AgentType
)
SELECT
	TRY_CONVERT(INT, e.EMPLOYEEID) AS EMPLOYEEID,
	NULLIF(LTRIM(RTRIM(e.FIRSTNAME)), '') AS FIRSTNAME,
	NULLIF(LTRIM(RTRIM(e.MIDNAME)), '') AS MIDNAME,
	NULLIF(LTRIM(RTRIM(e.LASTNAME)), '') AS LASTNAME,
	NULLIF(LTRIM(RTRIM(e.NICKNAME)), '') AS NICKNAME,
	NULLIF(LTRIM(RTRIM(e.POSITION)), '') AS POSITION,
	NULLIF(LTRIM(RTRIM(e.ADDRESS)), '') AS ADDRESS,
	NULLIF(LTRIM(RTRIM(e.CITY)), '') AS CITY,
	NULLIF(LTRIM(RTRIM(e.PROVINCE)), '') AS PROVINCE,
	NULLIF(LTRIM(RTRIM(e.ZIPCODE)), '') AS ZIPCODE,
	NULLIF(LTRIM(RTRIM(e.PHONE)), '') AS PHONE,
	e.BIRTHDATE,
	e.SEX,
	e.DATEHIRED,
	NULLIF(LTRIM(RTRIM(e.SSS)), '') AS SSS,
	TRY_CONVERT(INT, e.GROUP_ID) AS GROUP_ID,
	TRY_CONVERT(INT, e.AGENT_TYPE) AS AGENT_TYPE
FROM FoxProLegacy.dbo.EMPLOYEE AS e;
GO