USE IRYS;
GO
INSERT INTO dbo.Customers
(
	Id,
	CompanyName,
	ContactName,
	ContactTitle,
	Address,
	City,
	Province,
	ZipCode,
	Phone,
	Fax,
	Alarm,
	EmployeeId,
	PriceLvl,
	CreditLimit,
	Balance,
	Credit,
	InvBalance,
	TIN,
	AreaCode,
	CustomerCode,
	CustomerArea,
	CustomerAgent,
	AgentName,
	CustomerType,
	StartDate,
	SmCode,
	Term,
	TermCode,
	PType,
	Remarks
) 
SELECT
	TRY_CONVERT(INT, c.CUSTOMERID),
	NULLIF(LTRIM(RTRIM(c.COMPANYNAM)), ''),
	NULLIF(LTRIM(RTRIM(c.CONTACTNAM)), ''),
	NULLIF(LTRIM(RTRIM(c.CONTACTTIT)), ''),
	NULLIF(LTRIM(RTRIM(c.ADDRESS)), ''),
	NULLIF(LTRIM(RTRIM(c.CITY)), ''),
	NULLIF(LTRIM(RTRIM(c.PROVINCE)), ''),
	NULLIF(LTRIM(RTRIM(c.ZIPCODE)), ''),
	NULLIF(LTRIM(RTRIM(c.PHONE)), ''),
	NULLIF(LTRIM(RTRIM(c.FAX)), ''),
	c.ALARM,

	-- EMPLOYEEIDs in the Legacy were either white spaces or deleted PKs
	CASE
		WHEN NULLIF(LTRIM(RTRIM(c.EMPLOYEEID)),'') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, c.EMPLOYEEID) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.EMPLOYEE as e
			WHERE TRY_CONVERT(INT, e.EMPLOYEEID) = TRY_CONVERT(INT, c.EMPLOYEEID)
		) THEN NULL
		ELSE TRY_CONVERT(INT, c.EMPLOYEEID)
	END,

	TRY_CONVERT(INT, c.PRICELVL),
	c.CREDITLMT,
	c.BALANCE,
	c.CREDIT,
	c.INVBAL,
	NULLIF(LTRIM(RTRIM(c.TIN)), ''),

	-- Legacy data contained whitespaces or empty values
	CASE
	    WHEN NULLIF(LTRIM(RTRIM(c.AREACODE)), '') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, c.AREACODE) IS NULL THEN NULL
		ELSE TRY_CONVERT(INT, c.AREACODE)
	END,

	NULLIF(LTRIM(RTRIM(c.CUSCODE)), ''),
	NULLIF(LTRIM(RTRIM(c.CUSTAREA)), ''),
	NULLIF(LTRIM(RTRIM(c.CUSTAGENT)), ''),
	NULLIF(LTRIM(RTRIM(c.AGENTNAME)), ''),
	NULLIF(LTRIM(RTRIM(c.CUSTTYPE)), ''),
	c.STARTDATE,
	NULLIF(LTRIM(RTRIM(c.SMCODE)), ''),
	NULLIF(LTRIM(RTRIM(c.TERM)), ''),
	NULLIF(LTRIM(RTRIM(c.TERMCODE)), ''),
	NULLIF(LTRIM(RTRIM(c.PTYPE)), ''),
	NULLIF(LTRIM(RTRIM(CAST(c.REMARKS AS VARCHAR(MAX)))), '') AS REMARKS
FROM FoxProLegacy.dbo.CUSTOMERS AS c;
GO