USE IRYS;
GO
INSERT INTO dbo.Customers
(
	Id,
	CompanyName,
	ContactName,
	ContactTitle,
	Address,
	City,
	Province,
	ZipCode,
	Phone,
	Fax,
	Alarm,
	EmployeeId,
	PriceLvl,
	CreditLimit,
	Balance,
	Credit,
	InvBalance,
	TIN,
	AreaCode,
	CustomerCode,
	CustomerArea,
	CustomerAgent,
	AgentName,
	CustomerType,
	StartDate,
	SmCode,
	Term,
	TermCode,
	PType,
	Remarks
) 
SELECT
	TRY_CONVERT(INT, c.CUSTOMERID) AS CUSTOMERID,
	NULLIF(LTRIM(RTRIM(c.COMPANYNAM)), '') AS COMPANYNAM,
	NULLIF(LTRIM(RTRIM(c.CONTACTNAM)), '') AS CONTACTNAM,
	NULLIF(LTRIM(RTRIM(c.CONTACTTIT)), '') AS CONTACTTIT,
	NULLIF(LTRIM(RTRIM(c.ADDRESS)), '') AS ADDRESS,
	NULLIF(LTRIM(RTRIM(c.CITY)), '') AS CITY,
	NULLIF(LTRIM(RTRIM(c.PROVINCE)), '') AS PROVINCE,
	NULLIF(LTRIM(RTRIM(c.ZIPCODE)), '') AS ZIPCODE,
	NULLIF(LTRIM(RTRIM(c.PHONE)), '') AS PHONE,
	NULLIF(LTRIM(RTRIM(c.FAX)), '') AS FAX,
	c.ALARM,

	-- EMPLOYEEIDs in the Legacy were either white spaces or deleted PKs
	CASE
		WHEN NULLIF(LTRIM(RTRIM(c.EMPLOYEEID)),'') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, c.EMPLOYEEID) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.EMPLOYEE as e
			WHERE TRY_CONVERT(INT, e.EMPLOYEEID) = TRY_CONVERT(INT, c.EMPLOYEEID)
		) THEN NULL
		ELSE TRY_CONVERT(INT, c.EMPLOYEEID)
	END AS EMPLOYEEID,

	TRY_CONVERT(INT, c.PRICELVL) AS PRICELVL,
	c.CREDITLMT,
	c.BALANCE,
	c.CREDIT,
	c.INVBAL,
	NULLIF(LTRIM(RTRIM(c.TIN)), '') AS TIN,

	-- Legacy data contained whitespaces or empty values
	CASE
	    WHEN NULLIF(LTRIM(RTRIM(c.AREACODE)), '') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, c.AREACODE) IS NULL THEN NULL
		ELSE TRY_CONVERT(INT, c.AREACODE)
	END AS AREACODE,

	NULLIF(LTRIM(RTRIM(c.CUSCODE)), '') AS CUSCODE,
	NULLIF(LTRIM(RTRIM(c.CUSCODE)), '') CUSTAREA,
	NULLIF(LTRIM(RTRIM(c.CUSTAGENT)), '') AS CUSTAGENT,
	NULLIF(LTRIM(RTRIM(c.AGENTNAME)), '') AS AGENTNAME,
	NULLIF(LTRIM(RTRIM(c.CUSTTYPE)), '') AS CUSTTYPE,
	c.STARTDATE,
	NULLIF(LTRIM(RTRIM(c.SMCODE)), '') AS SMCODE,
	NULLIF(LTRIM(RTRIM(c.TERM)), '') AS TERM,
	NULLIF(LTRIM(RTRIM(c.TERMCODE)), '') AS TERMCODE,
	NULLIF(LTRIM(RTRIM(c.PTYPE)), '') AS PTYPE,
	NULLIF(LTRIM(RTRIM(CAST(c.REMARKS AS VARCHAR(MAX)))), '') AS REMARKS
FROM FoxProLegacy.dbo.CUSTOMERS AS c;
GO