USE IRYS;
GO
INSERT INTO dbo.Payments
(
	Id,
	CustomerId,
	PaymentModeId,
	Amount,
	PayDate,
	ReferenceNo,
	Remarks,
	PayStatusId,
	CreditsApplied,
	Adjust,
	EmployeeId,
	Notes,
	Collector
)
SELECT
	TRY_CONVERT(INT, p.PAYMENT_ID) AS PAYMENT_ID,

	-- Deleted customers in Legacy
	CASE
		WHEN TRY_CONVERT(INT, p.CUSTOMERID) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.CUSTOMERS AS c
			WHERE TRY_CONVERT(INT, c.CUSTOMERID) = TRY_CONVERT(INT, p.CUSTOMERID)
		) THEN NULL
		ELSE TRY_CONVERT(INT, p.CUSTOMERID)
	END AS CUSTOMERID,

	pm.Id AS PaymentModeId,
	p.AMOUNT,
	p.PDATE,
	NULLIF(LTRIM(RTRIM(p.REFNO)), '') AS REFNO,
	NULLIF(LTRIM(RTRIM(CAST(p.REMARKS AS VARCHAR(MAX)))), '') AS REMARKS,
	ps.Id AS PayStatusId,
	p.CREDITSAPP,
	p.ADJUST,

	-- Some non-NULL values and/or deleted Employees
	CASE
		WHEN NULLIF(LTRIM(RTRIM(p.EMPLOYEEID)), '') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, p.EMPLOYEEID) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.EMPLOYEE AS e
			WHERE TRY_CONVERT(INT, e.EMPLOYEEID) = TRY_CONVERT(INT, p.EMPLOYEEID)
		) THEN NULL
		ELSE TRY_CONVERT(INT, p.EMPLOYEEID)
	END AS EMPLOYEEID,

	NULLIF(LTRIM(RTRIM(CAST(p.NOTES AS VARCHAR(MAX)))), '') AS NOTES,

	-- Some non-NULL values and/or deleted Employees
	CASE
		WHEN NULLIF(LTRIM(RTRIM(p.COLLECTOR)), '') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, p.COLLECTOR) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.EMPLOYEE as e
			WHERE TRY_CONVERT(INT, e.EMPLOYEEID) = TRY_CONVERT(INT, p.COLLECTOR)
		) THEN NULL
		ELSE TRY_CONVERT(INT, p.COLLECTOR)
	END AS COLLECTOR
FROM FoxProLegacy.dbo.PAYMENTS AS p
LEFT JOIN IRYS.dbo.PaymentModes AS pm
	ON pm.ModeName = LTRIM(RTRIM(p.MODE))
LEFT JOIN IRYS.dbo.PayStatuses AS ps
	ON ps.StatusName = LTRIM(RTRIM(p.STATUS));
GO