USE IRYS;
GO
INSERT INTO dbo.Suppliers
(
	Id,
	SupplierName,
	ContactName,
	ContactTitle,
	Address,
	City,
	Province,
	ZipCode,
	Phone,
	Fax,
	Balance,
	PurchaseBalance,
	Credit,
	TIN
)
SELECT
	TRY_CONVERT(INT, s.SUPPLIERID) AS SUPPLIERID,
	LTRIM(RTRIM(s.SUPPLNAME)) AS SUPPLNAME,
	NULLIF(LTRIM(RTRIM(s.CONTNAME)), '') AS CONTNAME,
	NULLIF(LTRIM(RTRIM(s.CONTTITLE)), '') AS CONTTITLE,
	NULLIF(LTRIM(RTRIM(CAST(s.ADDRESS AS VARCHAR(MAX)))), '') AS ADDRESS,
	NULLIF(LTRIM(RTRIM(s.CITY)), '') AS CITY,
	NULLIF(LTRIM(RTRIM(s.PROVINCE)), '') AS PROVINCE,
	NULLIF(LTRIM(RTRIM(s.ZIPCODE)), '') AS ZIPCODE,
	NULLIF(LTRIM(RTRIM(s.PHONE)), '') AS PHONE,
	NULLIF(LTRIM(RTRIM(s.FAX)), '') AS FAX,
	s.BALANCE,
	s.PURCHBAL,
	s.CREDIT,
	NULLIF(LTRIM(RTRIM(s.TIN)), '') AS TIN
FROM FoxProLegacy.dbo.SUPPLIERS AS s;
GO