USE IRYS;
GO
INSERT INTO dbo.Suppliers
(
	Id,
	SupplierName,
	ContactName,
	ContactTitle,
	Address,
	City,
	Province,
	ZipCode,
	Phone,
	Fax,
	Balance,
	PurchaseBalance,
	Credit,
	TIN
)
SELECT
	TRY_CONVERT(INT, s.SUPPLIERID),
	LTRIM(RTRIM(s.SUPPLNAME)),
	NULLIF(LTRIM(RTRIM(s.CONTNAME)), ''),
	NULLIF(LTRIM(RTRIM(s.CONTTITLE)), ''),
	NULLIF(LTRIM(RTRIM(CAST(s.ADDRESS AS VARCHAR(MAX)))), ''),
	NULLIF(LTRIM(RTRIM(s.CITY)), ''),
	NULLIF(LTRIM(RTRIM(s.PROVINCE)), ''),
	NULLIF(LTRIM(RTRIM(s.ZIPCODE)), ''),
	NULLIF(LTRIM(RTRIM(s.PHONE)), ''),
	NULLIF(LTRIM(RTRIM(s.FAX)), ''),
	s.BALANCE,
	s.PURCHBAL,
	s.CREDIT,
	NULLIF(LTRIM(RTRIM(s.TIN)), '')
FROM FoxProLegacy.dbo.SUPPLIERS AS s;
GO