USE IRYS;
GO
INSERT INTO dbo.SupplierPayments
(
	Id,
	SupplierId,
	PaymentModeId,
	Amount,
	PayDate,
	ReferenceNo,
	Remarks,
	PayStatusId,
	CreditsApplied,
	Adjust,
	EmployeeId,
	Notes
)
SELECT
	TRY_CONVERT(INT, p.PAYMENT_ID) AS PAYMENT_ID,

	CASE
		WHEN NULLIF(LTRIM(RTRIM(p.SUPPLIERID)), '') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, p.SUPPLIERID) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.SUPPLIERS AS s
			WHERE TRY_CONVERT(INT, s.SUPPLIERID) = TRY_CONVERT(INT, p.SUPPLIERID)
		) THEN NULL
		ELSE TRY_CONVERT(INT, p.SUPPLIERID)
	END AS SUPPLIERID,

	-- They had empty values in MODE column
	CASE
		WHEN NULLIF(LTRIM(RTRIM(p.MODE)), '') IS NULL
			THEN 7 -- 'Unspecified'
		ELSE pm.Id
	END AS PaymentModeId,

	p.AMOUNT,
	p.PDATE,
	NULLIF(LTRIM(RTRIM(p.REFNO)), '') AS REFNO,
	NULLIF(LTRIM(RTRIM(CAST(p.REMARKS AS VARCHAR(MAX)))), '') AS REMARKS,

	CASE
		WHEN NULLIF(RTRIM(LTRIM(p.STATUS)), '') IS NULL
			THEN 3 -- 'UNSPECFIED'
		ELSE ps.Id 
	END AS StatusId,

	p.CREDITSAPP,
	p.ADJUST,

	CASE
		WHEN NULLIF(LTRIM(RTRIM(p.EMPLOYEEID)), '') IS NULL THEN NULL
		WHEN TRY_CONVERT(INT, p.EMPLOYEEID) IS NULL THEN NULL
		WHEN NOT EXISTS (
			SELECT 1
			FROM FoxProLegacy.dbo.EMPLOYEE AS e
			WHERE TRY_CONVERT(INT, e.EMPLOYEEID) = TRY_CONVERT(INT, p.EMPLOYEEID)
		) THEN NULL
		ELSE TRY_CONVERT(INT, p.EMPLOYEEID)
	END AS EMPLOYEEID,

	NULLIF(LTRIM(RTRIM(CAST(p.NOTES AS VARCHAR(MAX)))), '') AS NOTES
FROM FoxProLegacy.dbo.PAYMENT2 AS p
LEFT JOIN IRYS.dbo.PaymentModes AS pm
	ON pm.ModeName = LTRIM(RTRIM(p.MODE))
LEFT JOIN IRYS.dbo.PayStatuses AS ps
	ON ps.StatusName = LTRIM(RTRIM(p.STATUS))
GO