export const items = [
    {
        id: 10001,
        itemName: "Red Monobloc Chair",
        stocks: 78,
        badStocks: 0,
        unitId: 1,
        comm: "",
        terms: "",
        loc: "",
        categoryId: 1,
        wholesalePrice: 250.31,
        wholesaleDiscount: 0,
        retail1Price: 0,
        retail1Discount: 0,
        retail2Price: 0,
        retail2Discount: 0,
        purchasePrice: 0,
        purchaseDiscount: 0,
        specialPrice: 0,
        specialDiscount: 0,
        averageCost: 250.31         // we definitely don't need to store this, just compute it
    },
    {
        id: 10002,
        itemName: "Plastic Folding Table",
        stocks: 34,
        badStocks: 1,
        unitId: 1,
        comm: "",
        terms: "",
        loc: "",
        categoryId: 4,
        wholesalePrice: 750.00,
        wholesaleDiscount: 0,
        retail1Price: 0,
        retail1Discount: 0,
        retail2Price: 0,
        retail2Discount: 0,
        purchasePrice: 0,
        purchaseDiscount: 0,
        specialPrice: 0,
        specialDiscount: 0,
        averageCost: 750.00
    },
    {
        id: 10003,
        itemName: "Steel Cabinet",
        stocks: 6,
        badStocks: 0,
        unitId: 1,
        comm: "",
        terms: "",
        loc: "",
        categoryId: 3,
        wholesalePrice: 3200.50,
        wholesaleDiscount: 0,
        retail1Price: 0,
        retail1Discount: 0,
        retail2Price: 0,
        retail2Discount: 0,
        purchasePrice: 0,
        purchaseDiscount: 0,
        specialPrice: 0,
        specialDiscount: 0,
        averageCost: 3200.50
    },
    {
        id: 10004,
        itemName: "Office Desk",
        stocks: 5,
        badStocks: 0,
        unitId: 1,
        comm: "",
        terms: "",
        loc: "",
        categoryId: 2,
        wholesalePrice: 1850.75,
        wholesaleDiscount: 0,
        retail1Price: 0,
        retail1Discount: 0,
        retail2Price: 0,
        retail2Discount: 0,
        purchasePrice: 0,
        purchaseDiscount: 0,
        specialPrice: 0,
        specialDiscount: 0,
        averageCost: 1850.75
    },
    {
        id: 10005,
        itemName: "Ergonomic Chair",
        stocks: 11,
        badStocks: 0,
        unitId: 1,
        comm: "",
        terms: "",
        loc: "",
        categoryId: 5,
        wholesalePrice: 1450.00,
        wholesaleDiscount: 0,
        retail1Price: 1399.00,
        retail1Discount: 0,
        retail2Price: 1499.00,
        retail2Discount: 0,
        purchasePrice: 1500.00,
        purchaseDiscount: 0,
        specialPrice: 1299.50,
        specialDiscount: 0,
        averageCost: 1450.00
    },
]

// helpers

export const getAllItems = () => { return items }

export const getItemById = (id) => items.find(i => i.id === id)