USE IRYS_Dev;
GO

---------------------------------------------------
---                CustomerArea                 ---
---------------------------------------------------
INSERT INTO dbo.CustomerArea
(
    AreaCode,
    AreaName
)
VALUES
    (1, 'Metro Manila'),
    (2, 'Rizal'),
    (3, 'Laguna'),
    (4, 'Cavite'),
    (5, 'Bulacan');
GO

---------------------------------------------------
---                  Employees                  ---
---------------------------------------------------
INSERT INTO dbo.Employees
(
    Id,
    FirstName,
    MiddleName,
    LastName,
    NickName,
    Position,
    Address,
    City,
    Province,
    ZipCode,
    Phone,
    BirthDate,
    Sex,
    DateHired,
    SSS,
    GroupId,
    AgentType
)
VALUES
    (
        1,
        'Miguel',
        'Santos',
        'Reyes',
        'Mig',
        'Sales Representative',
        '12 Sampaguita St.',
        'Marikina',
        'Metro Manila',
        '1800',
        '09170000001',
        '1990-03-15',
        'M',
        '2021-06-01',
        NULL,
        1,
        1
    ),
    (
        2,
        'Andrea',
        'Cruz',
        'Mendoza',
        'Andi',
        'Sales Representative',
        '45 Acacia Ave.',
        'Pasig',
        'Metro Manila',
        '1600',
        '09170000002',
        '1992-08-22',
        'F',
        '2022-01-10',
        NULL,
        1,
        1
    ),
    (
        3,
        'Daniel',
        NULL,
        'Navarro',
        'Dan',
        'Account Manager',
        '78 Narra St.',
        'Antipolo',
        'Rizal',
        '1870',
        '09170000003',
        '1988-11-07',
        'M',
        '2020-09-14',
        NULL,
        2,
        2
    ),
    (
        4,
        'Sofia',
        'Garcia',
        'Lim',
        NULL,
        'Sales Coordinator',
        '21 Molave St.',
        'Santa Rosa',
        'Laguna',
        '4026',
        '09170000004',
        '1995-01-30',
        'F',
        '2023-04-03',
        NULL,
        2,
        1
    ),
    (
        5,
        'Joshua',
        NULL,
        'Torres',
        'Josh',
        'Sales Supervisor',
        '9 Mahogany Rd.',
        'Dasmarinas',
        'Cavite',
        '4114',
        '09170000005',
        '1985-12-18',
        'M',
        '2019-02-18',
        NULL,
        1,
        2
    );
GO

---------------------------------------------------
---                  Customers                  ---
---------------------------------------------------
INSERT INTO dbo.Customers
(
    Id,
    CompanyName,
    ContactName,
    ContactTitle,
    Address,
    City,
    Province,
    ZipCode,
    Phone,
    Fax,
    Alarm,
    EmployeeId,
    PriceLvl,
    CreditLimit,
    Balance,
    Credit,
    InvBalance,
    TIN,
    AreaCode,
    CustomerCode,
    CustomerArea,
    CustomerAgent,
    AgentName,
    CustomerType,
    StartDate,
    SmCode,
    Term,
    TermCode,
    PType,
    Remarks
)
VALUES
    (
        1001,
        'Northstar Hardware Trading',
        'Paolo Rivera',
        'Purchasing Manager',
        '101 Commerce St.',
        'Marikina',
        'Metro Manila',
        '1800',
        '09180000001',
        NULL,
        0,
        1,
        1,
        100000.00,
        25000.00,
        0.00,
        7500.00,
        NULL,
        1,
        'CUS1001',
        'Metro',
        'REP01',
        'Miguel Reyes',
        'WHOLESALE',
        '2022-01-15',
        'MR',
        'D',
        '30',
        'C',
        'Sample customer for development testing.'
    ),
    (
        1002,
        'Silverline Office Supply',
        'Maria Santos',
        'Owner',
        '22 Rizal Ave.',
        'Antipolo',
        'Rizal',
        '1870',
        '09180000002',
        NULL,
        1,
        2,
        2,
        75000.00,
        12000.00,
        5000.00,
        3000.00,
        NULL,
        2,
        'CUS1002',
        'Rizal',
        'REP02',
        'Andrea Mendoza',
        'RETAIL',
        '2023-03-20',
        'AM',
        'C',
        '15',
        'C',
        'Preferred customer.'
    ),
    (
        1003,
        'Greenfield Food Distribution',
        'Carlo Mendoza',
        'Purchasing Officer',
        '88 Laguna Industrial Rd.',
        'Santa Rosa',
        'Laguna',
        '4026',
        '09180000003',
        NULL,
        0,
        3,
        1,
        150000.00,
        45000.00,
        0.00,
        12500.00,
        NULL,
        3,
        'CUS1003',
        'Laguna',
        'REP03',
        'Daniel Navarro',
        'WHOLESALE',
        '2021-11-08',
        'DN',
        'D',
        '30',
        'C',
        NULL
    ),
    (
        1004,
        'Harborview Equipment Co.',
        'Elena Cruz',
        'Operations Manager',
        '14 Portside Blvd.',
        'Bacoor',
        'Cavite',
        '4102',
        '09180000004',
        NULL,
        0,
        4,
        3,
        200000.00,
        10000.00,
        15000.00,
        5000.00,
        NULL,
        4,
        'CUS1004',
        'Cavite',
        'REP04',
        'Sofia Lim',
        'WHOLESALE',
        '2024-02-12',
        'SL',
        'D',
        '45',
        'C',
        'Credit account.'
    ),
    (
        1005,
        'Blue Oak General Store',
        'Nina Flores',
        'Manager',
        '57 Market Road',
        'Malolos',
        'Bulacan',
        '3000',
        '09180000005',
        NULL,
        0,
        5,
        1,
        50000.00,
        0.00,
        0.00,
        0.00,
        NULL,
        5,
        'CUS1005',
        'Bulacan',
        NULL,
        NULL,
        'RETAIL',
        '2024-07-01',
        NULL,
        'C',
        '15',
        'C',
        'No assigned customer agent yet.'
    ),
    (
        1006,
        'Pinecrest Builders Supply',
        'Victor Tan',
        'Purchasing Officer',
        '31 Builder Lane',
        'Quezon City',
        'Metro Manila',
        '1100',
        '09180000006',
        NULL,
        0,
        NULL,
        2,
        90000.00,
        18000.00,
        0.00,
        2500.00,
        NULL,
        NULL,
        'CUS1006',
        NULL,
        NULL,
        NULL,
        'WHOLESALE',
        '2025-01-06',
        NULL,
        'D',
        '30',
        'C',
        'Intentionally contains nullable employee and area references for testing.'
    ),
    (
        1007,
        'Cedar Point Supplies',
        'Rafael Diaz',
        'Owner',
        '19 Cedar Street',
        'Pasig',
        'Metro Manila',
        '1600',
        '09180000007',
        NULL,
        0,
        3,
        1,
        60000.00,
        5000.00,
        0.00,
        1500.00,
        NULL,
        1,
        'CUS1007',
        'Metro',
        'REP03',
        'Daniel Navarro',
        'RETAIL',
        '2025-05-19',
        'DN',
        'C',
        '15',
        'C',
        NULL
    ),
    (
        1008,
        'Summit Industrial Parts',
        'Angela Reyes',
        'Purchasing Manager',
        '63 Industry Ave.',
        'Meycauayan',
        'Bulacan',
        '3020',
        '09180000008',
        NULL,
        1,
        5,
        2,
        125000.00,
        32000.00,
        3000.00,
        8500.00,
        NULL,
        5,
        'CUS1008',
        'Bulacan',
        'REP05',
        'Joshua Torres',
        'WHOLESALE',
        '2023-09-11',
        'JT',
        'D',
        '30',
        'C',
        'Alarm enabled for testing.'
    );
GO